name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jacopocarlini/action-autotag@3.0.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          tag_prefix: "v"
